#!/bin/bash

# Configure sub-command Name
new_Accent="nyaa" # new command creates project
delete_Accent="nyee" # delete command deletes project
list_Accent="list" # list command, list available template

# DO NOT TOUCH
condition="$1"
message="$1"
Lang="$2"
ProjectName="$3"
curdir="$(pwd)"

easter_eggs() {
    echo " /\_/\ "
    echo "( o.o ) Nyaa"
    echo " > ^ <"
}

# Main Logic
if [[ "$condition" = "$new_Accent" ]]; then
    echo "nyaaaaaa $ProjectName..."
    mkdir -p "$curdir/$ProjectName"
    cp -r ~/.config/MonyekaTemplates/"$Lang"/* "$curdir/$ProjectName/"
    echo "nyaa."
    cd "$curdir/$ProjectName"
    git init
    git branch -m master development
    git add .
    git commit -m "Create development Branch"
    git branch release
    cd ..
    exit 0
elif [[ "$condition" = "$delete_Accent" && -n "$2" ]]; then
    echo "nyeeeeee $2..."
    sudo rm -r "$curdir/$2"
    echo "nyee."
    exit 1
elif [[ "$condition" = "$list_Accent" ]]; then
    ls ~/.config/MonyekaTemplates
    exit 0
elif [[ -n "$condition" && -z "$2" ]]; then
    git add .
    git commit -m "$message"
    exit 0
elif [[ -z "$condition" ]]; then
    easter_eggs
    exit 0
fi



